debian: Updated postinst such that sysctl failures are non-fatal to installation

diff --git a/host/cmake/debian/uhd-host.postinst b/host/cmake/debian/uhd-host.postinst
--- a/host/cmake/debian/uhd-host.postinst
+++ b/host/cmake/debian/uhd-host.postinst
@@ -8,7 +8,7 @@ if [ "$1" = "configure" ]; then
  fi
  # Apply usrp2 networking optimization
  if [ -x "`which sysctl 2>/dev/null`" ]; then
-   sysctl -p /etc/sysctl.d/uhd-usrp2.conf
+   sysctl -p /etc/sysctl.d/uhd-usrp2.conf || echo "Warning: Could not update sysctl settings for network devices."
  fi
 fi
 
