ci: Mark devtest as failure on SucceededWithIssues
This marks the job as a failure on SucceededWithIssues. This could be
from failure in device setup or other reasons.

Signed-off-by: Steven Koo <steven.koo@ni.com>

diff --git a/.ci/templates/job-uhd-devtest.yml b/.ci/templates/job-uhd-devtest.yml
--- a/.ci/templates/job-uhd-devtest.yml
+++ b/.ci/templates/job-uhd-devtest.yml
@@ -184,3 +184,10 @@ jobs:
       failTaskOnFailedTests: true
     displayName: Upload devtest results
     condition: always()
+
+  - script: |
+      echo "A previous step failed. See steps with warnings."
+      echo "Marking the overall build status as a failure."
+      exit 1
+    condition: in(variables['Agent.JobStatus'],  'SucceededWithIssues')
+    displayName: Mark build as failure
