Update to latest master

diff --git a/.ci/templates/job-uhd-devtest.yml b/.ci/templates/job-uhd-devtest.yml
--- a/.ci/templates/job-uhd-devtest.yml
+++ b/.ci/templates/job-uhd-devtest.yml
@@ -13,6 +13,8 @@ parameters:
     - make
 - name: uhdSrcDir
   type: string
+- name: uhdArtifactSource
+  type: string
 - name: redisHost
   type: string
 - name: dutMatrix
@@ -21,48 +23,150 @@ parameters:
 jobs:
 - job: uhd_devtest_${{ parameters.suiteName }}_${{ parameters.testOS }}
   displayName:  uhd devtest ${{ parameters.suiteName }} ${{ parameters.testOS }}
+  timeoutInMinutes: 90
   pool:
     name: de-dre-lab
     demands:
     - suiteName -equals ${{ parameters.suiteName }}
     - testOS -equals ${{ parameters.testOS }}
+    - device -equals $(devAgent)
   variables:
   - group: sdr-pipeline-vars
   strategy:
     matrix: ${{ parameters.dutMatrix }}
   workspace:
     clean: outputs
+
   steps:
   - checkout: self
     clean: true
+
   - task: InstallSSHKey@0
     displayName: 'Install Ettus SSH key'
     inputs:
       knownHostsEntry: '${{ parameters.knownHost }}'
       sshPublicKey: '$(ettus_ssh_pubkey)'
       sshKeySecureFile: 'id_rsa.ettus'
-  - download: current
-    artifact: ${{ parameters.testOS }}-${{ parameters.toolset }}
-    displayName: Download pipeline artifact ${{ parameters.testOS }}-${{ parameters.toolset }}
+
+  - script: |
+      if [ "${{ parameters.uhdArtifactSource }}" = "current" ]; then
+        echo '##vso[task.setvariable variable=uhd_artifact_directory]'$(Agent.BuildDirectory)
+      else
+        echo '##vso[task.setvariable variable=uhd_artifact_directory]'$(Agent.BuildDirectory)/${{ parameters.uhdArtifactSource }}
+      fi
+    displayName: Set uhddev pipeline artifact location
+
+  - download: ${{ parameters.uhdArtifactSource }}
+    artifact: uhddev-${{ parameters.testOS }}-${{ parameters.toolset }}
+    displayName: Download uhddev-${{ parameters.testOS }}-${{ parameters.toolset }} artifact
+
   - task: ExtractFiles@1
     inputs:
-      archiveFilePatterns: $(Pipeline.Workspace)/${{ parameters.testOS }}-${{ parameters.toolset }}/${{ parameters.testOS }}-${{ parameters.toolset }}.tar.gz
+      archiveFilePatterns: $(uhd_artifact_directory)/uhddev-${{ parameters.testOS }}-${{ parameters.toolset }}/uhddev-${{ parameters.testOS }}-${{ parameters.toolset }}.tar.gz
       destinationFolder: $(Build.BinariesDirectory)
       cleanDestinationFolder: true
+
+  - download: ${{ parameters.uhdArtifactSource }}
+    artifact: n3xx-images
+    # Only sync the bz2 sdimg since the bmap
+    # is incompatible with mender
+    patterns: |
+      **/*.bz2
+      fitImage-manufacturing
+    displayName: Download $(devType)-images artifact
+    condition: and(succeeded(), eq(variables.devType, 'n3xx'))
+
+  - download: ${{ parameters.uhdArtifactSource }}
+    artifact: e320-images
+    # Only sync the bz2 sdimg since the bmap
+    # is incompatible with mender
+    patterns: |
+      **/*.bz2
+      fitImage-manufacturing
+    displayName: Download $(devType)-images artifact
+    condition: and(succeeded(), eq(variables.devModel, 'e320'))
+
   - script: |
       cd $(Build.BinariesDirectory)/uhddev/build
       mkdir -p fpga_images
       rm -rf fpga_images/*
-      python3 utils/uhd_images_downloader.py -t $(devModel) -i fpga_images \
+      python3 utils/uhd_images_downloader.py -t $(devModel)_fpga -i fpga_images \
         -b $(sdr-fileserver)
+      if [ "$(devType)" = "b200" ]; then
+        python3 utils/uhd_images_downloader.py -t b2xx_common -i fpga_images \
+          -b $(sdr-fileserver)
+      fi
     displayName: Download FPGA Images
+
+  - script: |
+      mkdir -p $(Common.TestResultsDirectory)/devtest
+      cd $(Common.TestResultsDirectory)/devtest
+      export PATH=$(Build.BinariesDirectory)/uhddev/build/utils:$(Build.BinariesDirectory)/uhddev/build/examples:$PATH
+      export LD_LIBRARY_PATH=$(Build.BinariesDirectory)/uhddev/build/lib:$LD_LIBRARY_PATH
+      export UHD_IMAGES_DIR=$(Build.BinariesDirectory)/uhddev/build/fpga_images
+      python3 ${{ parameters.uhdSrcDir }}/.ci/utils/mutex_hardware.py \
+        --sdimage_sdmux $(devType),$(devModel),$(uhd_artifact_directory)/$(devType)-images/$(devSDImage),${{ parameters.uhdSrcDir }}/$(devLabgridConfig),$(devHostname) \
+        --fpgas $(devFpga) \
+        --sfp_addrs $(sfpAddrs) \
+        ${{ parameters.redisHost }} $(devName) \
+        "$(Build.BinariesDirectory)/uhddev/build/utils/uhd_usrp_probe --args addr=$(devAddr)" \
+        "python3 ${{ parameters.uhdSrcDir }}/host/tests/devtest/run_testsuite.py \
+          --src-dir ${{ parameters.uhdSrcDir }}/host/tests/devtest \
+          --devtest-pattern $(devtestPattern) --args addr=$(devAddr),type=$(devType) \
+          --build-type Release --build-dir $(Build.BinariesDirectory)/uhddev/build \
+          --python-interp python3 --xml"
+    continueOnError: true
+    condition: and(succeeded(), eq(variables.devType, 'n3xx'), eq(variables.devBus, 'ip'))
+    displayName: Run n3xx devtest on $(devName)
+
+  - script: |
+      mkdir -p $(Common.TestResultsDirectory)/devtest
+      cd $(Common.TestResultsDirectory)/devtest
+      export PATH=$(Build.BinariesDirectory)/uhddev/build/utils:$(Build.BinariesDirectory)/uhddev/build/examples:$PATH
+      export LD_LIBRARY_PATH=$(Build.BinariesDirectory)/uhddev/build/lib:$LD_LIBRARY_PATH
+      export UHD_IMAGES_DIR=$(Build.BinariesDirectory)/uhddev/build/fpga_images
+      python3 ${{ parameters.uhdSrcDir }}/.ci/utils/mutex_hardware.py \
+        --sdimage_tftp $(devType),$(devModel),$(uhd_artifact_directory)/e320-images/$(devSDImage),$(uhd_artifact_directory)/e320-images/$(devInitramfsImage),${{ parameters.uhdSrcDir }}/$(devLabgridConfig) \
+        --fpgas $(devFpga) \
+        --sfp_addrs $(sfpAddrs) \
+        ${{ parameters.redisHost }} $(devName) \
+        "$(Build.BinariesDirectory)/uhddev/build/utils/uhd_usrp_probe --args addr=$(devAddr)" \
+        "python3 ${{ parameters.uhdSrcDir }}/host/tests/devtest/run_testsuite.py \
+          --src-dir ${{ parameters.uhdSrcDir }}/host/tests/devtest \
+          --devtest-pattern $(devtestPattern) --args addr=$(devAddr),type=$(devType) \
+          --build-type Release --build-dir $(Build.BinariesDirectory)/uhddev/build \
+          --python-interp python3 --xml"
+    continueOnError: true
+    condition: and(succeeded(), eq(variables.devModel, 'e320'), eq(variables.devBus, 'ip'))
+    displayName: Run e320 devtest on $(devName)
+
+  - script: |
+      mkdir -p $(Common.TestResultsDirectory)/devtest
+      cd $(Common.TestResultsDirectory)/devtest
+      export PATH=$(Build.BinariesDirectory)/uhddev/build/utils:$(Build.BinariesDirectory)/uhddev/build/examples:$PATH
+      export LD_LIBRARY_PATH=$(Build.BinariesDirectory)/uhddev/build/lib:$LD_LIBRARY_PATH
+      export UHD_IMAGES_DIR=$(Build.BinariesDirectory)/uhddev/build/fpga_images
+      python3 ${{ parameters.uhdSrcDir }}/.ci/utils/mutex_hardware.py \
+        ${{ parameters.redisHost }} $(devName) \
+        "$(Build.BinariesDirectory)/uhddev/build/utils/uhd_usrp_probe --args serial=$(devSerial)" \
+        "$(Build.BinariesDirectory)/uhddev/build/utils/uhd_image_loader --args serial=$(devSerial),type=$(devType)" \
+        "python3 ${{ parameters.uhdSrcDir }}/host/tests/devtest/run_testsuite.py \
+          --src-dir ${{ parameters.uhdSrcDir }}/host/tests/devtest \
+          --devtest-pattern $(devtestPattern) --args serial=$(devSerial),type=$(devType) \
+          --build-type Release --build-dir $(Build.BinariesDirectory)/uhddev/build \
+          --python-interp python3 --xml"
+    continueOnError: true
+    condition: and(succeeded(), eq(variables.devType, 'b200'), eq(variables.devBus, 'usb'))
+    displayName: Run b2xx devtest on $(devName)
+
   - script: |
       mkdir -p $(Common.TestResultsDirectory)/devtest
       cd $(Common.TestResultsDirectory)/devtest
       export PATH=$(Build.BinariesDirectory)/uhddev/build/utils:$(Build.BinariesDirectory)/uhddev/build/examples:$PATH
       export LD_LIBRARY_PATH=$(Build.BinariesDirectory)/uhddev/build/lib:$LD_LIBRARY_PATH
       python3 ${{ parameters.uhdSrcDir }}/.ci/utils/mutex_hardware.py \
-        --jtag_x3xx $(jtagServer),$(jtagSerial),$(Build.BinariesDirectory)/uhddev/build/fpga_images/usrp_$(devModel)_fpga_$(devFpga).bit \
+        --jtag_x3xx $(devType),$(devModel),$(jtagServer),$(jtagSerial),$(Build.BinariesDirectory)/uhddev/build/fpga_images/ \
+        --fpgas $(devFpga) \
         ${{ parameters.redisHost }} $(devName) \
         "$(Build.BinariesDirectory)/uhddev/build/utils/uhd_usrp_probe --args addr=$(devAddr)" \
         "python3 ${{ parameters.uhdSrcDir }}/host/tests/devtest/run_testsuite.py \
@@ -72,7 +176,14 @@ jobs:
           --python-interp python3 --xml"
     continueOnError: true
     condition: and(succeeded(), eq(variables.devType, 'x300'), eq(variables.devBus, 'ip'))
-    displayName: Run devtest on $(devName) $(devFpga)
+    displayName: Run x3xx devtest on $(devName) $(devFpga)
+
+  - script: |
+      cat $(Common.TestResultsDirectory)/devtest/log*.log
+      echo ""
+    displayName: cat devtest log
+    condition: always()
+
   - script: |
       cd $(Common.TestResultsDirectory)/devtest
       python3 ${{ parameters.uhdSrcDir }}/.ci/utils/format_devtest_junitxml.py \
@@ -80,12 +191,37 @@ jobs:
         $(Common.TestResultsDirectory)/devtest/devtestresults.xml
     continueOnError: true
     displayName: Format devtest xml
+    condition: and(always(), eq(variables.devType, 'b200'))
+
+  - script: |
+      cd $(Common.TestResultsDirectory)/devtest
+      python3 ${{ parameters.uhdSrcDir }}/.ci/utils/format_devtest_junitxml.py \
+        --fpgas $(devFpga) \
+        $(Common.TestResultsDirectory)/devtest \
+        $(Common.TestResultsDirectory)/devtest/devtestresults.xml
+    continueOnError: true
+    displayName: Format devtest xml
+    condition: and(always(), ne(variables.devType, 'b200'))
+
+  - publish: $(Common.TestResultsDirectory)
+    artifact: test-logs-devtest-$(devName)-$(devFpga)-run$(System.JobAttempt)
+    displayName: Upload Test Logs
+    condition: always()
+
   - task: PublishTestResults@2
     inputs:
       testResultsFormat: 'JUnit'
       testResultsFiles: '$(Common.TestResultsDirectory)/devtest/devtestresults.xml'
-      testRunTitle: $(devName) $(devFpga) devtest
+      testRunTitle: $(devName) devtest
       buildConfiguration: 'Release'
       mergeTestResults: true
       failTaskOnFailedTests: true
     displayName: Upload devtest results
+    condition: always()
+
+  - script: |
+      echo "A previous step failed. See steps with warnings."
+      echo "Marking the overall build status as a failure."
+      exit 1
+    condition: in(variables['Agent.JobStatus'],  'SucceededWithIssues')
+    displayName: Mark build as failure
diff --git a/.ci/templates/job-uhd-streaming-tests.yml b/.ci/templates/job-uhd-streaming-tests.yml
--- a/.ci/templates/job-uhd-streaming-tests.yml
+++ b/.ci/templates/job-uhd-streaming-tests.yml
@@ -19,11 +19,16 @@ parameters:
     - 'smoke'
     - 'full'
     - 'stress'
+- name: uhdArtifactSource
+  type: string
+  default: current
+- name: xilinxLocation
+  type: string
 
 jobs:
 - job: uhd_streaming_tests_${{ parameters.suiteName }}
   displayName:  uhd streaming tests ${{ parameters.suiteName }}
-  timeoutInMinutes: 180
+  timeoutInMinutes: 300
   pool:
     name: de-dre-lab
     demands:
@@ -35,42 +40,184 @@ jobs:
   steps:
   - checkout: self
     clean: true
-  - download: current
-    artifact: ${{ parameters.testOS }}-${{ parameters.toolset }}
-    displayName: download pipeline artifact ${{ parameters.testOS }}-${{ parameters.toolset }}
+
+  - checkout: meta-ettus
+    clean: true
+
+  - script: |
+      if [ "${{ parameters.uhdArtifactSource }}" = "current" ]; then
+        echo '##vso[task.setvariable variable=uhd_artifact_directory]'$(Agent.BuildDirectory)
+      else
+        echo '##vso[task.setvariable variable=uhd_artifact_directory]'$(Agent.BuildDirectory)/${{ parameters.uhdArtifactSource }}
+      fi
+    displayName: Set uhddev pipeline artifact location
+
+  - script: |
+      rm -rf $(uhd_artifact_directory)/$(dutEmbeddedImagesArtifact)
+      rm -rf $(uhd_artifact_directory)/uhddev-${{ parameters.testOS }}-${{ parameters.toolset }}
+    displayName: Cleanup from prior run
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'))
+
+  - download: ${{ parameters.uhdArtifactSource }}
+    artifact: $(dutEmbeddedImagesArtifact)
+    displayName: Download $(dutEmbeddedImagesArtifact)
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'))
+
   - task: ExtractFiles@1
     inputs:
-      archiveFilePatterns: $(Pipeline.Workspace)/${{ parameters.testOS }}-${{ parameters.toolset }}/${{ parameters.testOS }}-${{ parameters.toolset }}.tar.gz
+      archiveFilePatterns: $(uhd_artifact_directory)/$(dutEmbeddedImagesArtifact)/u-boot-jtag-files.zip
+      destinationFolder: $(uhd_artifact_directory)/$(dutEmbeddedImagesArtifact)
+      cleanDestinationFolder: false
+      overwriteExistingFiles: true
+    displayName: Extract JTAG artifact
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'))
+
+  - download: ${{ parameters.uhdArtifactSource }}
+    artifact: uhddev-${{ parameters.testOS }}-${{ parameters.toolset }}
+    displayName: Download uhddev-${{ parameters.testOS }}-${{ parameters.toolset }} artifact
+
+  - task: ExtractFiles@1
+    inputs:
+      archiveFilePatterns: $(uhd_artifact_directory)/uhddev-${{ parameters.testOS }}-${{ parameters.toolset }}/uhddev-${{ parameters.testOS }}-${{ parameters.toolset }}.tar.gz
       destinationFolder: $(Build.BinariesDirectory)
       cleanDestinationFolder: true
+    displayName: Extract uhddev-${{ parameters.testOS }}-${{ parameters.toolset }} artifact
+
+  - script: |
+      cd $(Agent.TempDirectory)
+      python3 -m venv venv
+      source venv/bin/activate
+      echo '##vso[task.setvariable variable=USRP_EMB_VENV]'$(realpath venv)
+      echo '##vso[task.setvariable variable=USRP_EMB_IMAGE_PATH]'$(uhd_artifact_directory)/$(dutEmbeddedImagesArtifact)
+      echo '##vso[task.setvariable variable=USRP_EMB_FTDI_SERIAL]'$(uartSerial)
+      python3 -m pip install -U pip
+      pip3 install wheel
+      pip3 install --upgrade $(Build.SourcesDirectory)/meta-ettus-dev/contrib/test/usrp_emb
+    displayName: Create usrp_emb venv
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'))
+
+  - script: |
+      source ${{ parameters.xilinxLocation }}/settings64.sh
+      source $USRP_EMB_VENV/bin/activate
+      usrp_emb_x4xx_mender_update
+    displayName: Update device using Mender
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'))
+
+  - script: |
+      source $USRP_EMB_VENV/bin/activate
+      USRP_EMB_TARGET_IP=$(usrp_emb_x4xx_boot_linux)
+      echo Target IP is $USRP_EMB_TARGET_IP
+      echo '##vso[task.setvariable variable=USRP_EMB_TARGET_IP]'$USRP_EMB_TARGET_IP
+    displayName: Boot target, get mgmt IP
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'))
+
+  # Setting the timezone on the embedded device is
+  # required to make the test runtimes to look sane.
+  - script: |
+      export HOST_TIME_ZONE=$(cat /etc/timezone)
+      ssh-keygen -f ~/.ssh/known_hosts -R $USRP_EMB_TARGET_IP
+      ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "timedatectl set-timezone $HOST_TIME_ZONE"
+    displayName: Set timezone to Host
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'))
+
+  - script: |
+        sleep 60
+    displayName: Wait for device to finish booting
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'))
+
+  - script: |
+        ssh-keygen -f ~/.ssh/known_hosts -R $USRP_EMB_TARGET_IP
+        ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "uhd_image_loader --args addr=localhost,type=$(dutType),fpga=$(dutFPGA)"
+        sleep 60
+    displayName: Flash FPGA $(dutFPGA)
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'))
+
+  - script: |
+      export UHD_IMAGES_DIR=$(Build.BinariesDirectory)/uhddev/build-installed/share/uhd/images
+      $(Build.BinariesDirectory)/uhddev/build-installed/bin/uhd_images_downloader -t b2xx -t fw
+      $(Build.BinariesDirectory)/uhddev/build-installed/bin/uhd_images_downloader -t b210 -t fpga
+    displayName: Download B210 images
+    condition: and(succeeded(), eq(variables.dutType, 'B210'))
+
+  - script: |
+      export UHD_IMAGES_DIR=$(Build.BinariesDirectory)/uhddev/build-installed/share/uhd/images
+      $(Build.BinariesDirectory)/uhddev/build-installed/bin/uhd_images_downloader -t x310
+      openFPGALoader -c digilent --ftdi-serial $(jtagSerial) --ftdi-channel 0 $UHD_IMAGES_DIR/usrp_x310_fpga_$(dutFPGA).bit
+      EXITCODE=$?
+      echo "Waiting for device to boot"
+      sleep 30
+      exit $EXITCODE
+    displayName: Download and update X310 fpga
+    condition: and(succeeded(), eq(variables.dutType, 'X310'))
+
+  - script: |
+      ssh-keygen -f ~/.ssh/known_hosts -R $USRP_EMB_TARGET_IP
+      ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "ethtool -A sfp0 tx on"
+      ssh -o StrictHostKeyChecking=no -tt root@$USRP_EMB_TARGET_IP "ethtool -A sfp1 tx on"
+    displayName: Enable Tx Pause Frames on sfp0 and sfp1
+    condition: and(succeeded(), eq(variables.dutType, 'x4xx'), eq(variables.dutFPGA, 'CG_400'))
   - script: |
       cd ${{ parameters.uhdSrcDir }}/host/tests/streaming_performance
       sudo ./setup.sh --auto
       sleep 5
     displayName: setup interfaces for use without DPDK
+    condition: and(succeeded(), not(eq(variables.dutType, 'x4xx')))
   - script: |
+      echo "##[group]Printing Environment"
+      printenv
+      echo "##[endgroup]"
       set -x
-      export PYTHONPATH=${{ parameters.uhdSrcDir }}/host/tests/streaming_performance
       cd ${{ parameters.uhdSrcDir }}/host/tests/pytests
-      python3 -m pytest -s test_streaming.py -m "not dpdk" --dut_type $(dutType) --test_length ${{ parameters.testLength }} \
-        --addr $(dutAddr) --second_addr $(dutSecondAddr) --mgmt_addr $(dutMgmtAddr) \
-        --uhd_build_dir $(Build.BinariesDirectory)/uhddev/build --junitxml $(Common.TestResultsDirectory)/TEST-$(dutName).xml
+      # Disable creation of __pycache__ files using -B to avoid errors on clean up during next run
+      # as using sudo below creates them with root priveleges.
+      sudo -E LD_LIBRARY_PATH=$LD_LIBRARY_PATH PYTHONPATH=$PYTHONPATH python3 -B -m pytest -s test_streaming.py -m "not dpdk" \
+        --dut_type $(dutType) --test_length ${{ parameters.testLength }} \
+        --uhd_build_dir $(Build.BinariesDirectory)/uhddev/build --junitxml $(Common.TestResultsDirectory)/TEST-$(dutName).xml \
+        --addr $(dutAddr) --second_addr $(dutSecondAddr) --mgmt_addr $(dutMgmtAddr) --name $(dutNameId) \
+        --num_recv_frames $(dutNumRecvFrames) --num_send_frames $(dutNumSendFrames)
+    env:
+      UHD_CONFIG_FILE: $(config_file)
+      PYTHONPATH: ${{ parameters.uhdSrcDir }}/host/tests/streaming_performance
+      LD_LIBRARY_PATH: $(Build.BinariesDirectory)/uhddev/build-installed/lib
+      UHD_IMAGES_DIR: $(Build.BinariesDirectory)/uhddev/build-installed/share/uhd/images
     continueOnError: true
     displayName: Run streaming tests on $(dutName)
+    condition: and(succeeded(), not(eq(variables.dutType, 'x4xx')))
   - script: |
       cd ${{ parameters.uhdSrcDir }}/host/tests/streaming_performance
       sudo ./setup.sh --auto --dpdk
       sleep 5
     displayName: setup interfaces for use with DPDK
+    condition: and(succeeded(), not(eq(variables.dutType, 'B210')))
   - script: |
+      if [ "$(dutFPGA)" = "CG_400" ]; then
+        echo "##vso[task.setvariable variable=config_file]${{ parameters.uhdSrcDir }}/host/tests/pytests/uhd_configs/uhd_dpdk_100GbE.conf"
+        echo "Using 100 GbE UHD Config File"
+      else
+        echo "##vso[task.setvariable variable=config_file]${{ parameters.uhdSrcDir }}/host/tests/pytests/uhd_configs/uhd_dpdk_10GbE.conf"
+        echo "Using 10 GbE UHD Config File"
+      fi
+    displayName: select UHD config file for DPDK
+  - script: |
+      echo "##[group]Printing Environment"
+      printenv
+      echo "##[endgroup]"
       set -x
-      export PYTHONPATH=${{ parameters.uhdSrcDir }}/host/tests/streaming_performance
       cd ${{ parameters.uhdSrcDir }}/host/tests/pytests
-      sudo --preserve-env=PYTHONPATH python3 -m pytest -s test_streaming.py -m "dpdk" --dut_type $(dutType) --test_length ${{ parameters.testLength }} \
-        --addr $(dutAddr) --second_addr $(dutSecondAddr) --mgmt_addr $(dutMgmtAddr) \
-        --uhd_build_dir $(Build.BinariesDirectory)/uhddev/build --junitxml $(Common.TestResultsDirectory)/TEST-$(dutName)-dpdk.xml
+      # Disable creation of __pycache__ files using -B to avoid errors on clean up during next run
+      # as using sudo below creates them with root priveleges.
+      sudo -E LD_LIBRARY_PATH=$LD_LIBRARY_PATH PYTHONPATH=$PYTHONPATH python3 -B -m pytest -s test_streaming.py -m "dpdk" \
+        --dut_type $(dutType) --test_length ${{ parameters.testLength }} \
+        --uhd_build_dir $(Build.BinariesDirectory)/uhddev/build --junitxml $(Common.TestResultsDirectory)/TEST-$(dutName)-dpdk.xml \
+        --addr $(dutAddr) --second_addr $(dutSecondAddr) --mgmt_addr $(dutMgmtAddr) --name $(dutNameId)
+    env:
+      UHD_CONFIG_FILE: $(config_file)
+      PYTHONPATH: ${{ parameters.uhdSrcDir }}/host/tests/streaming_performance
+      LD_LIBRARY_PATH: $(Build.BinariesDirectory)/uhddev/build-installed/lib
+      UHD_IMAGES_DIR: $(Build.BinariesDirectory)/uhddev/build-installed/share/uhd/images
     continueOnError: true
     displayName: Run streaming tests with DPDK on $(dutName)
+    condition: and(succeeded(), not(eq(variables.dutType, 'B210')))
   - task: PublishTestResults@2
     inputs:
       testResultsFormat: 'JUnit'
@@ -80,4 +227,10 @@ jobs:
       mergeTestResults: true
       failTaskOnFailedTests: false
     displayName: Upload streaming test results
+  - script: |
+      echo "A previous step failed. See steps with warnings."
+      echo "Marking the overall build status as a failure."
+      exit 1
+    condition: in(variables['Agent.JobStatus'],  'SucceededWithIssues')
+    displayName: Mark build as failure
 
