ci: Mark SucceededWithIssues as failure
This marks the pipeline a failure if it gets into SucceededWithIssues.
We do this because there might be sections of the test we want
to continue running even if the previous step failed.

Signed-off-by: Steven Koo <steven.koo@ni.com>

diff --git a/.ci/templates/tests/templates/job-uhd-x4xx-hardware-tests.yml b/.ci/templates/tests/templates/job-uhd-x4xx-hardware-tests.yml
--- a/.ci/templates/tests/templates/job-uhd-x4xx-hardware-tests.yml
+++ b/.ci/templates/tests/templates/job-uhd-x4xx-hardware-tests.yml
@@ -307,3 +307,11 @@ jobs:
     artifact: test-logs-x4xx-hardware-$(dutName)-run$(System.JobAttempt)
     displayName: Upload Test Logs
     condition: always()
+
+  - script: |
+      echo "A previous step failed. See steps with warnings."
+      echo "Marking the overall build status as a failure."
+      exit 1
+    condition: in(variables['Agent.JobStatus'],  'SucceededWithIssues')
+    displayName: Mark build as failure
+
