ci: Update FPGA CI pipelines to match new image builder
- Removes target names for X3x0 and X4x0 builds (these are now encoded
  in the YAML file)
- Change the image core YAML file names referenced in the pipeline YAMLs
  to match the contents of fpga/usrp3/top/x?00/*.yml
- Remove X410_XG_100 image since it is not a shipping image
- Add image_core_name arguments for all E320, E31x, N3xx targets

diff --git a/fpga/.ci/templates/job-build-fpga.yml b/fpga/.ci/templates/job-build-fpga.yml
--- a/fpga/.ci/templates/job-build-fpga.yml
+++ b/fpga/.ci/templates/job-build-fpga.yml
@@ -81,6 +81,7 @@ jobs:
         # image builder! That's also why we install the image builder in the
         # same step as building the bitfile: To avoid having to run hwsetup.sh
         # twice.
+        echo "##[group]Setting up build environment..."
         source $(Build.SourcesDirectory)/uhddev/fpga/.ci/scripts/run_setup.sh ./
         pip3 install -U numpy mako "ruamel.yaml<0.18.0" jsonschema
         set -o xtrace
@@ -94,14 +95,30 @@ jobs:
           -DENABLE_DOXYGEN=OFF -DENABLE_MAN_PAGES=OFF -DENABLE_MANUAL=OFF
         /usr/bin/cmake --build $(Build.BinariesDirectory)/build_image_builder
         /usr/bin/cmake --install $(Build.BinariesDirectory)/build_image_builder
+        echo "##[group]Executing FPGA build..."
         # rfnoc_image_builder does not currently get installed to a bin/ folder
         # via pip, so we add it to PATH
         export PATH=$BUILD_BINARIESDIRECTORY/prefix/bin:$VIRTUAL_ENV/bin:$PATH
-        python3 ../../tools/utils/repeat_fpga_build.py --target $(target_name) --image-core $(image_core) --num $(max_attempts) --seed $(($(System.JobAttempt)-1)) --persistent
+        if [ -n "$TARGET_NAME" ]; then
+            export TARGET_ARG="--target $TARGET_NAME"
+        fi
+        if [ -z "$IMAGE_CORE_NAME" ]; then
+            echo "##vso[task.logissue type=error]image_core_name must be set for proper functioning of pipeline!"
+            exit 1
+        fi
+        python3 ../../tools/utils/repeat_fpga_build.py \
+            --image-core $(image_core) $TARGET_ARG $BITFILE_NAME_ARG \
+            --image-core-name $IMAGE_CORE_NAME \
+            --num $(max_attempts) --seed $(($(System.JobAttempt)-1)) --persistent
+        export BUILD_ARTIFACT_DIR=`ls | grep build-usrp`
+        echo "Build artifact dir: $BUILD_ARTIFACT_DIR"
+        echo "##vso[task.setvariable variable=BuildArtifactDir;isOutput=true]$BUILD_ARTIFACT_DIR"
+        pip3 uninstall -y uhd
       workingDirectory: ${{ parameters.top_dir }}
       env:
         PATCHES_PATH: $(sdr-vivado-patches)
       displayName: 'Build Target'
+      name: build_target
 
     # Publish the final result only if all previous steps passed
     - publish: ${{ parameters.top_dir }}/build
@@ -109,8 +126,8 @@ jobs:
       displayName: 'Publish FPGA'
 
     # Publish intermediate files.
-    - publish: ${{ parameters.top_dir }}/build-$(target_name)
-      artifact: 'Build artifacts $(target_name) (Attempt $(System.JobAttempt))'
+    - publish: ${{ parameters.top_dir }}/$(build_target.BuildArtifactDir)
+      artifact: 'Build artifacts for $(image_core) (Target $(target_name), Image core name $(image_core_name),  Attempt $(System.JobAttempt))'
       condition: and(always(), eq('${{ parameters.publish_int_files }}', true))
       displayName: 'Publish Build Directory'
 
@@ -118,3 +135,8 @@ jobs:
     - template: check_clean_repo_steps.yml
       parameters:
         directory: ${{ parameters.top_dir }}
+
+    - bash: |
+        make cleanall
+      workingDirectory: ${{ parameters.top_dir }}
+      displayName: 'Clean up build artifacts'
